# Generated by Django 4.2 on 2025-04-28 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(15)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status_progress',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESSE', 'In progress'), ('FINISHED', 'Finished')], default='TO_DO', max_length=12),
        ),
    ]
