# Generated by Django 4.2 on 2025-04-28 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0002_alter_customuser_age_alter_issue_status_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Age'),
        ),
    ]
