# Generated by Django 4.2 on 2025-05-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('C', 'Contributor')], default='C', max_length=1),
        ),
    ]
