# Generated by Django 4.2 on 2025-05-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0004_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_contributor', to='restapi_core.contributor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_project', to='restapi_core.project'),
        ),
    ]
