# Generated by Django 4.2 on 2025-05-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='contributor',
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='contributors',
            field=models.ManyToManyField(related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
