# Generated by Django 4.2 on 2025-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_core', '0008_rename_title_issue_name_remove_issue_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='archiv_contribs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
