# Generated by Django 4.2 on 2025-05-15 18:49

from django.db import migrations

def copy_contributors(apps, schema_editor):
    IssueMod = apps.get_model("restapi_core", "Issue" )

    # Geting all the contribs data and populate archiv_contribs
    for obj in IssueMod.objects.all():
        # whe use contributors.all() because contributors
        # is a ManyToMany field
        contribs = obj.contributors.all()
        archived = [{"id": str(c.pk)} for c in contribs]
        obj.archiv_contribs = archived
        obj.save(update_fields=['archiv_contribs'])


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('restapi_core', '0009_issue_archiv_contribs'),
    ]

    operations = [
        migrations.RunPython(copy_contributors, reverse),
    ]
